# Generated by Django 3.2.4 on 2021-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('kilometers', models.IntegerField()),
                ('owners', models.IntegerField()),
                ('fueltype', models.CharField(max_length=30)),
                ('dealer', models.CharField(max_length=30)),
                ('transmissiontype', models.CharField(max_length=60)),
            ],
        ),
    ]
